#A
add_lunch_combo nameless_anzu-userdebug
#D
add_lunch_combo nameless_d2lte-userdebug
add_lunch_combo nameless_d800-userdebug
add_lunch_combo nameless_d801-userdebug
add_lunch_combo nameless_d802-userdebug
add_lunch_combo nameless_d803-userdebug
#G
add_lunch_combo nameless_galaxysmtd-userdebug
add_lunch_combo nameless_galaxysl-userdebug
#H
add_lunch_combo nameless_haida-userdebug
add_lunch_combo nameless_hammerhead-userdebug
#I
add_lunch_combo nameless_i9100-userdebug
add_lunch_combo nameless_i9300-userdebug
add_lunch_combo nameless_i9500-userdebug
#J
add_lunch_combo nameless_jflte-userdebug
#L
add_lunch_combo nameless_ls980-userdebug
#N
add_lunch_combo nameless_n7000-userdebug
#P
add_lunch_combo nameless_p880-userdebug
add_lunch_combo nameless_p970-userdebug
#V
add_lunch_combo nameless_vs980-userdebug
