#D
add_lunch_combo nameless_d800-userdebug
add_lunch_combo nameless_d801-userdebug
add_lunch_combo nameless_d802-userdebug
add_lunch_combo nameless_d803-userdebug
#G
add_lunch_combo nameless_galaxysmtd-userdebug
#H
add_lunch_combo nameless_hammerhead-userdebug
#I
add_lunch_combo nameless_i9100-userdebug
add_lunch_combo nameless_i9300-userdebug
#J
add_lunch_combo nameless_jflte-userdebug
add_lunch_combo nameless_jflteatt-userdebug
add_lunch_combo nameless_jfltecan-userdebug
add_lunch_combo nameless_jfltecri-userdebug
add_lunch_combo nameless_jfltecsp-userdebug
add_lunch_combo nameless_jfltespr-userdebug
add_lunch_combo nameless_jfltetmo-userdebug
add_lunch_combo nameless_jflteusc-userdebug
add_lunch_combo nameless_jfltevzw-userdebug
add_lunch_combo nameless_jfltexx-userdebug
#L
add_lunch_combo nameless_ls980-userdebug
#N
add_lunch_combo nameless_n7000-userdebug
#P
add_lunch_combo nameless_p970-userdebug
add_lunch_combo nameless_p880-userdebug
#V
add_lunch_combo nameless_vs980-userdebug
