#!/system/bin/sh

# odex /system/app
FILES=/system/app/*;
for f in /system/app/*;
do
	dexopt --preopt /system/app/$f.odex /system/app/$f.odex u=y;
done;

# odex /system/priv-app
FILES=/system/priv-app/*;
for f in /system/priv-app/*;
do
	dexopt --preopt /system/priv-app/$f.odex /system/priv-app/$f.odex u=y;
done;
