#!/system/bin/sh

# odex /system/app
for f in /system/app/*;
do
	/system/bin/dexopt --preopt $f ${f//.apk/.odex} u=y 2> /dev/null;
done;

# odex /system/priv-app
for f in /system/priv-app/*;
do
	/system/bin/dexopt --preopt $f ${f//.apk/.odex} u=y 2> /dev/null;
done;

# remove proplematic odexes
rm -rf /system/app/Superuser.apk.odex
