PRODUCT_VERSION_MAJOR = 6.0.1
PRODUCT_VERSION_MINOR = 1.0
PRODUCT_VERSION_MAINTENANCE = beta
ifdef NAMELESS_BUILD_EXTRA
    NAMELESS_POSTFIX := -$(NAMELESS_BUILD_EXTRA)
endif
ifndef NAMELESS_BUILD_TYPE
ifeq ($(NAMELESS_RELEASE),true)
    NAMELESS_BUILD_TYPE := OFFICIAL
    PLATFORM_VERSION_CODENAME := OFFICIAL
    NAMELESS_POSTFIX := -$(shell date +"%Y%m%d")
else
    NAMELESS_BUILD_TYPE := UNOFFICIAL
    PLATFORM_VERSION_CODENAME := UNOFFICIAL
	NAMELESS_POSTFIX := -$(shell date +"%Y%m%d")
endif
endif

ifeq ($(NAMELESS_BUILD_TYPE),DM)
    NAMELESS_POSTFIX := -$(shell date +"%Y%m%d")
endif
	
ifndef NAMELESS_POSTFIX
    NAMELESS_POSTFIX := -$(shell date +"%Y%m%d-%H%M")
endif

PLATFORM_VERSION_CODENAME := $(NAMELESSL_BUILD_TYPE)

# Set all versions
NAMELESS_VERSION := NAMELESS-$(PRODUCT_VERSION_MINOR)-$(NAMELESS_BUILD_TYPE)$(NAMELESS_POSTFIX)
NAMELESS_MOD_VERSION := NAMELESS-$(NAMELESS_BUILD)-$(PRODUCT_VERSION_MINOR)-$(NAMELESS_BUILD_TYPE)$(NAMELESS_POSTFIX)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    ro.nameless.version=$(NAMELESS_VERSION) \
    ro.modversion=$(NAMELESS_MOD_VERSION) \
    ro.nameless.buildtype=$(NAMELESS_BUILD_TYPE)
